[package]
authors = [ "Evan Gipson" ]
name = "craft-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.9.5"
serde = "1.0.219"
serde_derive = "1.0.219"
rand = "0.9.2"
logger = { path = "libs/logger" }