[[class_tiers]]
classes = ["chest"]
prefixes = [
	{ affix = "phys-thorns-dmg", tiers = [
		{ min = [101, 151], max = [146, 220], item_level = 74, weight = 1000 },
		{ min = [64, 97], max = [97, 145], item_level = 63, weight = 1000 },
		{ min = [40, 60], max = [61, 92], item_level = 48, weight = 1000 },
		{ min = [24, 35], max = [35, 53], item_level = 38, weight = 1000 },
		{ min = [11, 16], max = [15, 23], item_level = 19, weight = 1000 },
		{ min = [5, 7], max = [7, 10], item_level = 10, weight = 1000 },
		{ min = [1, 2], max = [3, 4], item_level = 1, weight = 1000 },
	]},
	{ affix = "armor", tiers = [
		{ range = [101, 110], item_level = 75, weight = 1000 },
		{ range = [92, 100], item_level = 65, weight = 1000 },
		{ range = [80, 90], item_level = 60, weight = 1000 },
		{ range = [68, 79], item_level = 54, weight = 1000 },
		{ range = [56, 67], item_level = 46, weight = 1000 },
		{ range = [43, 55], item_level = 35, weight = 1000 },
		{ range = [27, 42], item_level = 16, weight = 1000 },
		{ range = [15, 26], item_level = 2, weight = 1000 },
	]},
	{ affix = "hybrid-armor", tiers = [
		{ hybrid = [{ affix = "armor", range = [39, 42]}, { affix = "flat-armor", range = [70, 86] }], item_level = 78, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [33, 38]}, { affix = "flat-armor", range = [54, 69] }], item_level = 60, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [27, 32]}, { affix = "flat-armor", range = [40, 53] }], item_level = 46, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [21, 26]}, { affix = "flat-armor", range = [30, 39] }], item_level = 33, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [14, 20]}, { affix = "flat-armor", range = [12, 29] }], item_level = 16, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [6, 13]}, { affix = "flat-armor", range = [7, 11] }], item_level = 8, weight = 1000 },
	]},
	{ affix = "hybrid-armor-life", tiers = [
		{ hybrid = [{ affix = "armor", range = [39, 42]}, { affix = "max-life", range = [42, 49] }], item_level = 78, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [33, 38]}, { affix = "max-life", range = [33, 41] }], item_level = 60, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [27, 32]}, { affix = "max-life", range = [26, 32] }], item_level = 46, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [21, 26]}, { affix = "max-life", range = [20, 25] }], item_level = 33, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [14, 20]}, { affix = "max-life", range = [11, 19] }], item_level = 16, weight = 1000 },
		{ hybrid = [{ affix = "armor", range = [6, 13]}, { affix = "max-life", range = [7, 11] }], item_level = 8, weight = 1000 },
	]},
	{ affix = "flat-armor", tiers = [
		{ range = [257, 276], item_level = 79, weight = 1000 },
		{ range = [226, 256], item_level = 75, weight = 1000 },
		{ range = [203, 225], item_level = 65, weight = 1000 },
		{ range = [161, 202], item_level = 60, weight = 1000 },
		{ range = [123, 160], item_level = 54, weight = 1000 },
		{ range = [103, 122], item_level = 46, weight = 1000 },
		{ range = [83, 102], item_level = 33, weight = 1000 },
		{ range = [69, 82], item_level = 25, weight = 1000 },
		{ range = [51, 68], item_level = 16, weight = 1000 },
		{ range = [28, 50], item_level = 8, weight = 1000 },
		{ range = [16, 27], item_level = 1, weight = 1000 },
	]},
	{ affix = "max-life", tiers = [
		{ range = [200, 214], item_level = 80, weight = 1000 },
		{ range = [190, 199], item_level = 75, weight = 1000 },
		{ range = [175, 189], item_level = 70, weight = 1000 },
		{ range = [150, 174], item_level = 65, weight = 1000 },
		{ range = [120, 149], item_level = 60, weight = 1000 },
		{ range = [100, 119], item_level = 54, weight = 1000 },
		{ range = [85, 99], item_level = 46, weight = 1000 },
		{ range = [70, 84], item_level = 38, weight = 1000 },
		{ range = [60, 69], item_level = 33, weight = 1000 },
		{ range = [40, 59], item_level = 24, weight = 1000 },
		{ range = [30, 39], item_level = 16, weight = 1000 },
		{ range = [20, 29], item_level = 6, weight = 1000 },
		{ range = [10, 19], item_level = 1, weight = 1000 },
	]},
	{ affix = "spirit", tiers = [
		{ range = [57, 61], item_level = 78, weight = 100 },
		{ range = [54, 56], item_level = 65, weight = 200 },
		{ range = [51, 53], item_level = 60, weight = 300 },
		{ range = [47, 50], item_level = 54, weight = 400 },
		{ range = [43, 46], item_level = 46, weight = 500 },
		{ range = [38, 42], item_level = 33, weight = 500 },
		{ range = [34, 37], item_level = 25, weight = 500 },
		{ range = [30, 33], item_level = 16, weight = 500 },
	]},
]
suffixes = [
	{ affix = "life-regen", tiers = [
		{ range = [33, 36], item_level = 81, weight = 1000 },
		{ range = [29, 32], item_level = 75, weight = 1000 },
		{ range = [23, 28], item_level = 68, weight = 1000 },
		{ range = [18, 22], item_level = 58, weight = 1000 },
		{ range = [13, 18], item_level = 47, weight = 1000 },
		{ range = [9, 13], item_level = 35, weight = 1000 },
		{ range = [6, 9], item_level = 26, weight = 1000 },
		{ range = [4, 6], item_level = 17, weight = 1000 },
		{ range = [3, 4], item_level = 11, weight = 1000 },
		{ range = [2, 3], item_level = 5, weight = 1000 },
		{ range = [1, 2], item_level = 1, weight = 1000 },
	]},
	{ affix = "attr-req", tiers = [
		{ value = 35, item_level = 60, weight = 900 },
		{ value = 30, item_level = 52, weight = 900 },
		{ value = 25, item_level = 40, weight = 900 },
		{ value = 20, item_level = 32, weight = 900 },
		{ value = 15, item_level = 24, weight = 900 },
	]},
	{ affix = "bleed-duration", tiers = [
		{ range = [56, 60], item_level = 76, weight = 500 },
		{ range = [51, 55], item_level = 64, weight = 500 },
		{ range = [46, 50], item_level = 50, weight = 500 },
		{ range = [41, 45], item_level = 37, weight = 500 },
		{ range = [36, 40], item_level = 21, weight = 500 },
	]},
	{ affix = "ignite-duration", tiers = [
		{ range = [56, 60], item_level = 76, weight = 500 },
		{ range = [51, 55], item_level = 64, weight = 500 },
		{ range = [46, 50], item_level = 50, weight = 500 },
		{ range = [41, 45], item_level = 37, weight = 500 },
		{ range = [36, 40], item_level = 21, weight = 500 },
	]},
	{ affix = "poison-duration", tiers = [
		{ range = [56, 60], item_level = 76, weight = 500 },
		{ range = [51, 55], item_level = 64, weight = 500 },
		{ range = [46, 50], item_level = 50, weight = 500 },
		{ range = [41, 45], item_level = 37, weight = 500 },
		{ range = [36, 40], item_level = 21, weight = 500 },
	]},
	{ affix = "str", tiers = [
		{ range = [31, 33], item_level = 74, weight = 1000 },
		{ range = [28, 30], item_level = 66, weight = 1000 },
		{ range = [25, 27], item_level = 55, weight = 1000 },
		{ range = [21, 24], item_level = 44, weight = 1000 },
		{ range = [17, 20], item_level = 33, weight = 1000 },
		{ range = [13, 16], item_level = 22, weight = 1000 },
		{ range = [9, 12], item_level = 11, weight = 1000 },
		{ range = [5, 8], item_level = 1, weight = 1000 },
	]},
	{ affix = "stun-threshold", tiers = [
		{ range = [254, 304], item_level = 72, weight = 800 },
		{ range = [207, 254], item_level = 63, weight = 800 },
		{ range = [164, 206], item_level = 54, weight = 800 },
		{ range = [125, 163], item_level = 45, weight = 800 },
		{ range = [98, 124], item_level = 36, weight = 800 },
		{ range = [73, 97], item_level = 29, weight = 800 },
		{ range = [50, 72], item_level = 22, weight = 800 },
		{ range = [30, 49], item_level = 15, weight = 800 },
		{ range = [12, 29], item_level = 8, weight = 800 },
		{ range = [6, 11], item_level = 1, weight = 800 },
	]},
	{ affix = "armor-ele-dmg", tiers = [
		{ range = [44, 50], item_level = 81, weight = 1000 },
		{ range = [38, 43], item_level = 66, weight = 1000 },
		{ range = [32, 37], item_level = 48, weight = 1000 },
		{ range = [26, 31], item_level = 36, weight = 1000 },
		{ range = [20, 25], item_level = 16, weight = 1000 },
		{ range = [14, 19], item_level = 1, weight = 1000 },
	]},
	{ affix = "chaos-res", tiers = [
		{ range = [24, 27], item_level = 81, weight = 250 },
		{ range = [20, 23], item_level = 68, weight = 250 },
		{ range = [16, 19], item_level = 56, weight = 250 },
		{ range = [12, 15], item_level = 44, weight = 250 },
		{ range = [8, 11], item_level = 30, weight = 250 },
		{ range = [4, 7], item_level = 16, weight = 250 },
	]},
	{ affix = "cold-res", tiers = [
		{ range = [41, 45], item_level = 82, weight = 1000 },
		{ range = [36, 40], item_level = 71, weight = 1000 },
		{ range = [31, 35], item_level = 60, weight = 1000 },
		{ range = [26, 30], item_level = 50, weight = 1000 },
		{ range = [21, 25], item_level = 38, weight = 1000 },
		{ range = [16, 20], item_level = 26, weight = 1000 },
		{ range = [11, 15], item_level = 14, weight = 1000 },
		{ range = [6, 10], item_level = 1, weight = 1000 },
	]},
	{ affix = "fire-res", tiers = [
		{ range = [41, 45], item_level = 82, weight = 1000 },
		{ range = [36, 40], item_level = 71, weight = 1000 },
		{ range = [31, 35], item_level = 60, weight = 1000 },
		{ range = [26, 30], item_level = 50, weight = 1000 },
		{ range = [21, 25], item_level = 38, weight = 1000 },
		{ range = [16, 20], item_level = 26, weight = 1000 },
		{ range = [11, 15], item_level = 14, weight = 1000 },
		{ range = [6, 10], item_level = 1, weight = 1000 },
	]},
	{ affix = "lightning-res", tiers = [
		{ range = [41, 45], item_level = 82, weight = 1000 },
		{ range = [36, 40], item_level = 71, weight = 1000 },
		{ range = [31, 35], item_level = 60, weight = 1000 },
		{ range = [26, 30], item_level = 50, weight = 1000 },
		{ range = [21, 25], item_level = 38, weight = 1000 },
		{ range = [16, 20], item_level = 26, weight = 1000 },
		{ range = [11, 15], item_level = 14, weight = 1000 },
		{ range = [6, 10], item_level = 1, weight = 1000 },
	]},
]