modifiers = [
	{ name = "+#% physical damage", id = "phys-dmg", tags = ["damage", "physical"] },
	{ name = "# to # physical thorns damage", id = "phys-thorns-dmg", tags = ["damage", "physical"] },
	{ name = "#% increased armor", id = "armor", tags = ["defences"] },
	{ name = "+# to armor", id = "flat-armor", tags = ["defences"] },
	{ name = "#% increased armor, +# armor", id = "hybrid-armor", tags = ["defences"] },
	{ name = "#% increased armor, +# maximum life", id = "hybrid-armor-life", tags = ["life", "defences"] },
	{ name = "+# maximum life", id = "max-life", tags = ["life", "defences", "armor"] },
	{ name = "+# to spirit", id = "spirit" },
	{ name = "# life regeneration per second", id = "life-regen", tags = ["life regen", "life"]},
	{ name = "#% reduced attribute requirements", id = "attr-req" },
	{ name = "#% reduced duration of bleeding on you", id = "bleed-duration", tags = ["bleed", "physical", "ailment"] },
	{ name = "#% reduced ignite duration on you", id = "ignite-duration", tags = ["elemental", "fire", "ailment"] },
	{ name = "#% reduced poison duration on you", id = "poison-duration", tags = ["poison", "chaos", "ailment"] },
	{ name = "+# stun threshold", id = "stun-threshold" },
	{ name = "+#% armor also applies to elemental damage", id = "armor-ele-dmg", tags = ["defences", "elemental"] },
	{ name = "+# to strength", id = "str", tags = ["attribute"] },
	{ name = "+# to intelligence", id = "int", tags = ["attribute"] },
	{ name = "+# to dexterity", id = "dex", tags = ["attribute"] },
	{ name = "+# to all attributes", id = "all-attr", tags = ["attribute"] },
	{ name = "+#% to chaos resistance", id = "chaos-res", tags = ["chaos", "resistance"] },
	{ name = "+#% to cold resistance", id = "cold-res", tags = ["cold", "elemental", "resistance"] },
	{ name = "+#% to fire resistance", id = "fire-res", tags = ["fire", "elemental", "resistance"] },
	{ name = "+#% to lightning resistance", id = "lightning-res", tags = ["lightning", "elemental", "resistance"] },
]